# Use root/example as user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - auth-net

  authenticator:
    build: './'
    container_name: authenticator
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - JWT_EXPIRE_LENGTH=3600000
      - spring.jpa.hibernate.ddl-auto=none
    networks:
      - auth-net
    ports:
      - '8080:8080'


networks:
  auth-net:
    driver: bridge

volumes:
  postgresdata: