ALTER TABLE
    IF EXISTS users
ADD
    COLUMN created_by VARCHAR(50);

ALTER TABLE
    IF EXISTS users
ADD
    COLUMN created_date TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE
    IF EXISTS users
ADD
    COLUMN last_modified_by VARCHAR(50);

ALTER TABLE
    IF EXISTS users
ADD
    COLUMN last_modified_date TIMESTAMP(6) WITH TIME ZONE;