spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?createDatabaseIfNotExist=true&currentSchema=authenticator
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456} 
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        default-schema: authenticator
        formatSql: ${SHOW_SQL:false}

  flyway:
    enabled: true
    locations: db/postgresql
    schemas: authenticator

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  show-actuator: true
  pathsToMatch: 
    - /api/v1/**
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    use-root-path: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}

cors:
  originPatterns: http://localhost:8080,http://localhost:4200

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:Secrettest3}
      expire-length: ${JWT_EXPIRE_LENGTH:3600000}
      expire-refresh-length: ${JWT_EXPIRE_REFRESH_LENGTH:43200000}
