spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authenticator_db}?createDatabaseIfNotExist=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456} 
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        formatSql: true

  flyway:
    enabled: true
    locations: db/postgresql

springdoc:
  pathsToMatch: 
    - /api/v1/**
  swagger-ui:
    use-root-path: true

cors:
  originPatterns: http://localhost:8080,http://localhost:4200

security:
  jwt:
    token:
      secret-key: Secrettest3
      expire-length: 3600000
