spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authenticator_db}?createDatabaseIfNotExist=true&currentSchema=authenticator
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456} 
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        default-schema: authenticator
        formatSql: true

  flyway:
    enabled: true
    locations: db/postgresql
    schemas: authenticator

springdoc:
  pathsToMatch: 
    - /api/v1/**
  swagger-ui:
    use-root-path: true

logging:
  level:
    root: INFO

cors:
  originPatterns: http://localhost:8080,http://localhost:4200

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:Secrettest3}
      expire-length: ${JWT_EXPIRE_LENGTH:3600000}
      expire-refresh-length: ${JWT_EXPIRE_REFRESH_LENGTH:43200000}
