CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(150) NOT NULL,
    `password` varchar(255) NOT NULL,
    token_reset_password UUID,
    `enabled` boolean NOT NULL,
    account_non_expired boolean,
    account_non_locked boolean,
    credentials_non_expired boolean,
    token_reset_password_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    token_reset_password_expiration_date TIMESTAMP,
    id_person bigint,
    id_profile bigint,
    PRIMARY KEY (id)
);

ALTER TABLE
    IF EXISTS users
ADD
    CONSTRAINT unique_users_username UNIQUE (username);

ALTER TABLE
    IF EXISTS users
ADD
    CONSTRAINT fk_users_id_person FOREIGN KEY (id_person) REFERENCES person;

ALTER TABLE
    IF EXISTS users
ADD
    CONSTRAINT fk_users_id_profile FOREIGN KEY (id_profile) REFERENCES `profile`;