ALTER TABLE
    IF EXISTS users
ADD
    COLUMN created_by VARCHAR(50);

ALTER TABLE
    IF EXISTS users
ADD
    COLUMN created_date TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE
    IF EXISTS users
ADD
    COLUMN last_modified_by VARCHAR(50);

ALTER TABLE
    IF EXISTS users
ADD
    COLUMN last_modified_date TIMESTAMP(6) WITH TIME ZONE;

CREATE TABLE person_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype TINYINT,
    address VARCHAR(255),
    name VARCHAR(150),
    PRIMARY KEY (rev, id)
);

CREATE TABLE revinfo (
    rev INTEGER generated by default as identity,
    revtstmp BIGINT,
    PRIMARY KEY (rev)
);

CREATE TABLE users_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype TINYINT,
    account_non_expired BOOLEAN,
    account_non_locked BOOLEAN,
    credentials_non_expired BOOLEAN,
    enabled BOOLEAN,
    password VARCHAR(255),
    username VARCHAR(50),
    id_person BIGINT,
    PRIMARY KEY (rev, id)
);