CREATE SCHEMA IF NOT EXISTS AUTHENTICATOR;

CREATE TABLE basic_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) NOT NULL,
    `password` varchar(255) NOT NULL,
    `enabled` boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE
    IF EXISTS basic_token
ADD
    CONSTRAINT unique_basic_token_username UNIQUE (username);