CREATE TABLE `param` (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `name` VARCHAR(50) NOT NULL,
    `description` VARCHAR(255),
    `value` VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE
    IF EXISTS param
ADD
    CONSTRAINT unique_param_name UNIQUE (name);