version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:17-jdk-alpine
    steps:
      - checkout
      - run:
          name: Grant execute permissions to mvnw
          command: |
            chmod +x mvnw
      - run:
          name: Build and Test
          command: |
            ./mvnw clean install -DskipTests -Dtest=!com.moraes.authenticator.integration.*

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
