version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:17-jdk-alpine
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build
