version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build
