name: Authenticator CI
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t suleimanmoraes/authenticator:${{ env.VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # - name: Push Docker image latest
      #   run: docker push suleimanmoraes/authenticator

      - name: Push Docker image
        run: docker push suleimanmoraes/authenticator:${{ env.VERSION }}